# Generated by Django 5.2.3 on 2025-08-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.CharField(choices=[('install', 'Application Install'), ('chat', 'Chat Message'), ('file', 'File Download'), ('system', 'System Event')], default='chat', max_length=20),
        ),
    ]
